spring.application.name=lab
spring.datasource.url=jdbc:postgresql://localhost:5432/casedesk
spring.datasource.username=nsix
spring.datasource.password=fundtrail@123
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-vire=false
